In [32]:
import numpy as np
import pandas as pd
wine = pd.read_csv('/Users/aashraylalnakarmi/Downloads/archive (8)/winemag-data-130k-v2.csv')

In [7]:
pd.set_option("display.max_rows", 10)

In [8]:
wine

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [9]:
wine.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [11]:
desc = wine.loc[:,'description']

In [12]:
desc

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [13]:
type(desc)

pandas.core.series.Series

In [14]:
first_description = desc[0]

In [15]:
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [17]:
first_row = wine.iloc[0,:]

In [18]:
first_row

Unnamed: 0                                                               0
country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
                                               ...
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, Length: 14, dtype: object

In [19]:
wine.loc[0:9,'description']

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

In [20]:
sample_reviews = wine.iloc[[1,2,3,5,8]]

In [21]:
sample_reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

In [33]:
df = pd.DataFrame({
    'Country': ['Italy','Portugol','US','US'],
    'province' : ['Sicily & Sardinia','Duoro','California','New York'],
    'region_1' : ['Etna',np.nan,'Napa Valley','Finger Lakes'],
    'refion_2' : [np.nan,np.nan,'Napa','Finger Lakes']
},index=[0,1,10,100])

In [34]:
df

      Country           province      region_1      refion_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugol              Duoro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

In [36]:
wine.loc[0:999,['country','variety']]

       country         variety
0        Italy     White Blend
1     Portugal  Portuguese Red
2           US      Pinot Gris
3           US        Riesling
4           US      Pinot Noir
..         ...             ...
995      Italy     White Blend
996      Italy           Syrah
997  Australia          Shiraz
998         US      Pinot Gris
999         US        Riesling

[1000 rows x 2 columns]

In [45]:
italian_wines = wine.loc[(wine.country == 'Italy')].head(10)

In [46]:
italian_wines

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
26,26,Italy,Pretty aromas of yellow flower and stone fruit...,Dalila,87,13.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Stemmari 2013 Dalila White (Terre Siciliane),White Blend,Stemmari
27,27,Italy,"Aromas recall ripe dark berry, toast and a whi...",NaN,87,10.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Stemmari 2013 Nero d'Avola (Terre Siciliane),Nero d'Avola,Stemmari
28,28,Italy,"Aromas suggest mature berry, scorched earth, a...",Mascaria Barricato,87,17.0,Sicily & Sardinia,Cerasuolo di Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2011 Mascaria Barricato (Cera...,Red Blend,Terre di Giurfo
31,31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta

In [48]:
wine.loc[(wine.points >= 95) & (wine.country.isin(['Australia','New Zealand']))].head(50)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
346,346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
348,348,Australia,Deep mahogany. Dried fig and black tea on the ...,Grand,97,100.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Grand Muscat (R...,Muscat,Chambers Rosewood Vineyards
349,349,Australia,"RunRig is always complex, and the 2012 doesn't...",RunRig,97,225.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 RunRig Shiraz-Viognier (Barossa),Shiraz-Viognier,Torbreck
356,356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109434,109434,Australia,D'Arenberg's lineup of single-vineyard Shiraze...,The Swinging Malaysian Single Vineyard,96,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 The Swinging Malaysian Single ...,Shiraz,D'Arenberg
122421,122421,Australia,"Despite this wine's weight and richness, it re...",Amon-Ra Unfiltered,96,110.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Amon-Ra Unfiltered Shiraz (Baros...,Shiraz,Glaetzer
122430,122430,Australia,These blends are traditional in Australia—they...,Anaperenna,95,80.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Anaperenna Shiraz-Cabernet Sauvi...,Shiraz-Cabernet Sauvignon,Glaetzer
122507,122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
122939,122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck

In [49]:
wine

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [50]:
wine.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [55]:
wine.loc[wine["points"] == 100, "designation"]

345                    Rare
7335      Occhio di Pernice
36528                  Brut
39286               Masseto
42197           Barca-Velha
                ...
113929           Royal City
114972     Nacional Vintage
118058              La Muse
122935                  NaN
123545          Bionic Frog
Name: designation, Length: 19, dtype: object

In [57]:
wine.points.mean()

np.float64(88.44713820775404)

In [58]:
wine.province.unique()

array(['Sicily & Sardinia', 'Douro', 'Oregon', 'Michigan',
       'Northern Spain', 'Alsace', 'Rheinhessen', 'California', 'Mosel',
       'Other', 'Mendoza Province', 'Virginia', 'Beaujolais',
       'Colchagua Valley', 'Southern Italy', 'Maule Valley', 'Bordeaux',
       'Maipo Valley', 'Washington', 'Central Italy', 'Champagne',
       'Burgundy', 'South Australia', 'Tejo', 'Rapel Valley', 'Galicia',
       'France Other', 'Tuscany', 'Burgenland', 'New York',
       'Leyda Valley', 'Piedmont', 'Stellenbosch',
       'Simonsberg-Stellenbosch', 'Walker Bay', 'Alentejano',
       'Central Spain', 'Southwest France', 'Aconcagua Valley',
       'Loncomilla Valley', 'Marlborough', 'Northeastern Italy',
       'Casablanca Valley', 'Veneto', 'Western Cape', 'Judean Hills',
       'Alentejo', 'Coastal Region', 'Rhône Valley', 'Galilee',
       'Beira Atlantico', 'Tokaj', 'Leithaberg', 'Santorini', 'Kremstal',
       'Catalonia', 'Recas', "Hawke's Bay", 'Curicó Valley',
       'Limarí Valley', 'Colchagua Costa', 'Languedoc-Roussillon',
       'Provence', 'Victoria', 'Rheingau', 'Tokaji', 'Naoussa',
       'Valle de Guadalupe', 'Central Valley', 'Lontué Valley',
       'Italy Other', 'Weinviertel', 'Thermenregion', 'Niederösterreich',
       'Wagram', 'Loire Valley', 'Lombardy', 'Ontario',
       'Österreichischer Sekt', 'Kamptal', 'Steiermark', 'Südsteiermark',
       'Crete', 'Vinho Verde', 'Idaho', 'Western Australia', 'Levante',
       'Martinborough', 'Central Otago', 'Lisboa', 'Texas',
       'Península de Setúbal', 'Australia Other', 'Tasmania', 'Franken',
       'Ahr', 'Nahe', nan, 'Dealu Mare', 'Port', 'Darling', 'Chile',
       'Südoststeiermark', 'Corinth', 'Halkidiki', 'Thrace', 'Pfalz',
       'Robertson', 'Dan', 'Northwestern Italy', 'Andalucia',
       'Awatere Valley', 'Wiener Gemischter Satz', 'Wachau',
       'Pennsylvania', 'Swartland', 'Dão', 'Wagram-Donauland',
       'Rio Claro', 'Villány', 'Cachapoal Valley', 'Jidvei', 'America',
       'Traisental', 'Bairrada', 'Negev Hills', 'Ribatejano', 'Duriense',
       'New Jersey', 'Beiras', 'Spanish Islands', 'Upper Galilee',
       'Vinho Espumante', 'Epanomi', 'Nemea', 'Peloponnese',
       'Aconcagua Costa', 'Moravia', 'Slovenia', 'Terras do Dão',
       'Beira Interior', 'Panciu', 'Bío Bío Valley', 'Romania',
       'Portuguese Table Wine', 'Minho', 'Missouri', 'New Mexico',
       'Nevada', 'Bucelas', 'Peumo', 'San Antonio', 'Carnuntum',
       'Estremadura', 'Canterbury', 'Spain Other', 'Drama', 'Ella Valley',
       'Moselle Luxembourgeoise', 'Württemberg', 'Baden', 'Pangeon',
       'Elqui Valley', 'Wairau Valley', 'Istria', 'Peljesac', 'Kakheti',
       'Canelones', 'England', 'Marchigue', 'Paarl', 'Durbanville',
       'Weinland Österreich', 'Mantinia', 'Chalkidiki', 'Lebanon',
       'Setubal', 'Mosel-Saar-Ruwer', 'Colorado', 'Pocerina',
       'British Columbia', 'Puente Alto', 'Kumeu', 'Trás-os-Montes',
       'Shomron', 'Rapsani', 'Vienna', 'New South Wales', 'Nelson',
       'Waipara Valley', 'Constantia', 'Arizona', 'Pinto Bandeira',
       'Primorska', 'Moldova', 'Uruguay', 'Zenata', 'South Africa',
       'Massachusetts', 'Ohio', 'Ica', 'San Vicente', 'Nashik',
       'Franschhoek', 'South Island', 'Atlantida', 'Thracian Valley',
       'Tarnave', 'Vipavska Dolina', 'Bekaa Valley', 'Elgin',
       'Itata Valley', 'Table wine', 'Samson', 'Madeira', 'Cyprus',
       'Pageon', 'Vinho Espumante de Qualidade', 'Wellington',
       'Danube River Plains', 'Gisborne', 'Obidos', 'Wairarapa',
       'Armenia', 'Santa Cruz', 'Korčula', 'Viile Timisului', 'Illinois',
       'Aegean', 'Simonsberg-Paarl', 'Juanico', 'Black Sea Coastal',
       'Santa Catarina', 'Overberg', 'Atalanti Valley', 'Sebes',
       'Moscatel de Setúbal', 'Macedonia', 'Ribatejo', 'Germany',
       'Palmela', 'Galil', 'Kras', 'Croatia', 'Waipara', 'Olifants River',
       'Montevideo', 'Campanha', 'Israel', 'Neusiedlersee', 'Hungary',
       'Lolol Valley', 'Cauquenes Valley', 'Groenekloof', 'Alenquer',
       'Goriska Brda', 'Murfatlar', 'Moscatel do Douro',
       'Washington-Oregon', 'New Zealand', 'Serra Gaúcha', 'San Jose',
       'Vale dos Vinhedos', 'Mittelburgenland', 'Lutzville Valley',
       'North Carolina', 'Apalta', 'Malleco', 'Guerrouane', 'Valais',
       'Choapa Valley', 'Georgia', 'Ankara', 'Samos', 'Mittelrhein',
       'Eisenberg', 'Sagrada Familia', 'Austria', 'Mostar', 'Iowa',
       'Tulbagh', 'Cederberg', 'Hemel en Aarde', 'Ceres Plateau',
       'Bot River', 'Patras', 'Korinthia', 'Greece', 'San Clemente',
       'Podunavlje', 'Florina', 'Buin', 'Haut-Judeé', 'Ukraine',
       'Terras do Sado', 'Maipo Valley-Colchagua Valley', 'Brazil',
       'Breedekloof', 'Leyda Valley-Maipo Valley', 'Vermont',
       'Switzerland', 'Waitaki Valley', 'Eger', 'Golan Heights',
       'Fruška Gora', 'Philadelphia', 'Muzla', 'Mátra', 'Pirque', 'Negev',
       'Pitsilia Mountains', 'East Coast', 'Mavrodaphne of Patras',
       'Attica', 'Progreso', 'Elazığ-Diyarbakir', 'Jonkershoek Valley',
       'Tikves', 'Vale Trentino', 'Turkey', 'Waiheke Island', 'Molina',
       'Serra do Sudeste', 'Dalmatian Coast', 'Eilandia',
       'Dealurile Munteniei', 'Thraki', 'Curicó and Maipo Valleys',
       'Štajerska', 'Middle and South Dalmatia', 'Kentucky', 'Župa',
       'Pafos', 'Monemvasia', 'Szekszárd', 'Elazığ', 'Cappadocia',
       'Kutjevo', 'Ismarikos', 'Connecticut', 'Sithonia',
       'Curicó and Leyda Valleys', 'Agioritikos',
       'Casablanca-Curicó Valley', 'Piekenierskloof', 'Elim', 'Malgas',
       'Beotia', 'Algarve', 'Retsina', 'Amindeo', 'Coelemu',
       'Cape South Coast', 'Sopron', 'Bulgaria', 'North Dalmatia',
       'Northern Cape', 'Vinho da Mesa', 'Hvar', 'Cephalonia', 'Lemesos',
       'Cahul', 'Cyclades', 'Breede River Valley', 'Ticino',
       'Vlootenburg', 'Brda', 'Dingač', 'Morocco', 'Achaia',
       'Polkadraai Hills', 'Rhode Island', 'Amyndeon', 'Vânju Mare',
       'Hrvatsko Primorje', 'Central Greece', 'Dolenjska',
       'Österreichischer Perlwein', 'Requinoa',
       'Mavrodaphne de Cephalonie', 'Goumenissa', 'Portugal', 'Messinia',
       'Lakonia', 'Markopoulo', 'Vinho Licoroso', 'Paardeberg',
       'San Antonio de las Minas Valley', 'Krania Olympus', 'Corinthia',
       'Slovenska Istra', 'Commandaria', 'Gladstone', 'Jerusalem Hills',
       'Mount Athos', 'Colares', 'Helderberg',
       'Casablanca & Leyda Valleys', 'Dealurile Hușilor', 'Urla-Thrace',
       'Südburgenland', 'Cape Peninsula', 'Codru Region', 'Sterea Ellada',
       'Muscat of Patras', 'Imathia', 'Alenteo', 'Canada Other',
       'Letrinon', 'Muscat of Kefallonian', 'Thessalikos', 'Hawaii',
       'China', 'Limnos', 'Egypt', 'Viile Timis', 'Devon Valley', 'Krk',
       'Arcadia', 'Cape Agulhas', 'Kathikas', 'Vin de Pays de Velvendo',
       'Landwein Rhein', 'Lesbos', 'Távora-Varosa', 'Neuchâtel'],
      dtype=object)

In [60]:
wine.taster_name.value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
                      ...
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, Length: 19, dtype: int64